Trigger refs/changes/* fetch when submodule update fails
Change-Id: Ic5be22717717e0a5af33474a9cfb275a7b6f203f

diff --git a/jenkins/gerrit-verifier.yaml b/jenkins/gerrit-verifier.yaml
--- a/jenkins/gerrit-verifier.yaml
+++ b/jenkins/gerrit-verifier.yaml
@@ -53,10 +53,9 @@
             done
           }
           git submodule init
-          # Fetch submodules ONLY if last commit included a change in a submodule
-          ((git log -p -1 | grep -q -i subproject) && fetch_submodules) || true
+          # Fetch submodules refs/changes as fallback action of a submodule update failure
           echo "Updating all submodules ..."
-          git submodule update
+          git submodule update || ( fetch_submodules && git submodule update )
 
 - job-template:
     name: '{name}-{mode}'
