Buildifier: Implement format check for build files
Change-Id: I0e5bc60141a53bb17d314ede094162303162ad27

diff --git a/jenkins/gerrit-verifier.yaml b/jenkins/gerrit-verifier.yaml
--- a/jenkins/gerrit-verifier.yaml
+++ b/jenkins/gerrit-verifier.yaml
@@ -171,6 +171,28 @@
            bazel test //polygerrit-ui/app:lint_test --test_output errors
            bazel test //polygerrit-ui/app:polylint_test --test_output errors
          fi
+      - shell: |
+         #!/bin/bash -xe
+         cd gerrit
+         BUILD_FILES=$(git show --diff-filter=AM --name-only HEAD | grep --regex "WORKSPACE\|BUILD")
+         if [[ -s ${BUILD_FILES} ]]; then
+             NUM_BUILD_FILES=$(echo ${BUILD_FILES} | wc -w)
+             echo "Running buildifier on ${NUM_BUILD_FILES} files"
+             BUILDIFIER_OUTPUT_FILE="$(mktemp)_buildifier_output.log"
+             rm -rf ${BUILDIFIER_OUTPUT_FILE}
+             buildifier -showlog -v -mode=check ${BUILD_FILES} 2>&1 | tee ${BUILDIFIER_OUTPUT_FILE}
+             if [[ -s ${BUILDIFIER_OUTPUT_FILE} ]]; then
+                 echo "FAIL: buildifier found errors and/or warnings in above BUILD files."
+                 # TODO(davido): tkdiff must be installed for buildifier -showlog to work properly
+                 #echo "buildifier suggested the following changes:"
+                 #buildifier -showlog -v -mode=diff ${BUILD_FILES}
+                 echo "Please fix manually or run buildifier <file> to auto-fix."
+                 exit 1
+             else
+                 echo "PASS: No buildifier errors or warnings were found"
+                 exit 0
+             fi
+         fi
 
 - job:
     name: 'Gerrit-verifier-change'
